### ISSUE TITLE
Could not load type 'System.Runtime.InteropServices.UCOMIEnumMoniker' from assembly

### ISSUE THREAD

**Issue by GabrielBottari** [MyCaffe/WebCam#1]
Hello,

I've run the sample application which works great on a standalone project. But when I try and run it in my own project, I get:

System.TypeLoadException
  HResult=0x80131522
  Message=Could not load type 'System.Runtime.InteropServices.UCOMIEnumMoniker' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
  Source=DirectX.Capture
  StackTrace:
   at DirectX.Capture.FilterCollection.getFilters(Guid category)
   at DirectX.Capture.FilterCollection..ctor(Guid category)
   at DirectX.Capture.Filters..ctor()
   at WebCam.WebCam..ctor()
   at EScreenProtector.Services.CameraService..ctor()
   at EScreenProtector.FaceDetector.FaceDetectorService..ctor()
   at EScreenProtector.Windows.MainWindow..ctor(Boolean containsData)
   at EScreenProtector.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at EScreenProtector.App.Main()

The only difference I can tell is the sample runs as a .NET framework application, and mine as a .NET core. Even then, in those cases, the library should still run under .NET framework. Any pointers? @ZoroDerVonCodier

**Comment by ZoroDerVonCodier** [comment]
Hi @GabrielBottari ,

According to https://weblog.west-wind.com/posts/2019/Jan/22/COM-Object-Access-and-dynamic-in-NET-Core-2x, you might want to try .NET core 3.0 or above.  

I did see that when adding the WebCam to a .NET core 2.1 project, the NUGET package gets a warning stating that 'This package may not be fully compatible with your project.'.  

The DirectShow and DShowNET do use COM which may be causing the incompatibility as noted by Rick's blog note referenced above.

Hope this helps!

**Comment by GabrielBottari** [comment]
Hello again @ZoroDerVonCodier ,

I actually figured out the issue. You're using deprecated classes from System.Runtime.InteropServices such as UCOMIEnumMoniker and UCOMIMoniker. After replacing those, it runs like a charm on both .NET Framework and .NET core. I commited those changes, but am unable to push a branch to your repo and make a pull request as I get 403. Let me know if you want me to push the changes by opening up the repo. 

Cheers!

**Comment by ZoroDerVonCodier** [comment]
@GabrielBottari ,

Awesome work!  I gave you access to make pull requests.  After you make your pull request, I will review and add it to the project.  Since we just make a big release, we will get this into our next WebCam NUGET release due to occur in about a month when we synchronize all of our releases.

**Comment by GabrielBottari** [comment]
@ZoroDerVonCodier Did you omit to give me write access? (Except to protected branch master) As I can't push a branch to make a pull request.

**Comment by ZoroDerVonCodier** [comment]
@GabrielBottari , my bad - try now, you have write access.

**Comment by ZoroDerVonCodier** [comment]
Once you have a chance to verify on your side, I will close this out.

**Comment by GabrielBottari** [comment]
I've been using the updated library on .NET core. Works great!
